import { TRPCError } from "@trpc/server";
import { and, asc, desc, eq, gt, gte, inArray, isNull, like, lte, or, sql } from "drizzle-orm";
import { nanoid } from "nanoid";
import { z } from "zod";
import { academicYears, announcements, assignmentCompletions, assignments, auditLogs, calendarEvents, feeStructures, guardians, messages, notifications, recentViews, schoolClasses, schools, studentFeeAccounts, studentGuardians, studentIdCards, students, subjects, teachers, users } from "../../drizzle/schema";
import { getDb, writeAuditLog } from "../db";
import { administrativeRoles, requireRole } from "../permissions";
import { storagePut } from "../storage";
import { getTenantContext } from "../_core/tenant";
import { protectedProcedure, publicProcedure, router } from "../_core/trpc";

const staffRoles: Array<"super_admin" | "principal" | "deputy_principal" | "teacher" | "class_teacher" | "bursar"> = ["super_admin", "principal", "deputy_principal", "teacher", "class_teacher", "bursar"];
const academicStaffRoles: Array<"super_admin" | "principal" | "deputy_principal" | "teacher" | "class_teacher"> = ["super_admin", "principal", "deputy_principal", "teacher", "class_teacher"];
const leadershipRoles: Array<"super_admin" | "principal" | "deputy_principal"> = ["super_admin", "principal", "deputy_principal"];
const audienceSchema = z.enum(["school", "form", "class", "teachers", "parents", "students"]);
const formSchema = z.enum(["Form 1", "Form 2", "Form 3", "Form 4"]);
const attachmentSchema = z.object({ fileName: z.string().min(1).max(200), mimeType: z.string().min(3).max(120), data: z.string().min(8).max(2_000_000) }).optional();

async function operatingSchool() {
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database service is unavailable." });
  const tenant = getTenantContext();
  if (!tenant?.schoolId) throw new TRPCError({ code: "FORBIDDEN", message: "Your account is not assigned to a school." });
  const [school] = await db.select().from(schools).where(eq(schools.id, tenant.schoolId)).limit(1);
  if (!school || school.id !== tenant.schoolId) throw new TRPCError({ code: "FORBIDDEN", message: "Your school access is unavailable." });
  return { db, school };
}

async function linkedStudentIds(userId: number, role: string, schoolId: number) {
  const db = await getDb();
  if (!db) return [];
  if (role === "student") return (await db.select({ id: students.id }).from(students).where(and(eq(students.userId, userId), eq(students.schoolId, schoolId)))).map(row => row.id);
  if (role === "parent") return (await db.select({ id: studentGuardians.studentId }).from(guardians).innerJoin(studentGuardians, eq(guardians.id, studentGuardians.guardianId)).where(and(eq(guardians.userId, userId), eq(guardians.schoolId, schoolId)))).map(row => row.id);
  return [];
}

async function storeAttachment(schoolId: number, scope: string, attachment: z.infer<typeof attachmentSchema>) {
  if (!attachment) return {};
  const bytes = Buffer.from(attachment.data, "base64");
  if (!bytes.length || bytes.length > 1_000_000) throw new TRPCError({ code: "BAD_REQUEST", message: "Attachment must be a valid file no larger than 1 MB." });
  const name = attachment.fileName.replace(/[^a-zA-Z0-9._-]/g, "_").slice(-120) || "attachment";
  const { key } = await storagePut(`schools/${schoolId}/${scope}/${Date.now()}-${name}`, bytes, attachment.mimeType);
  return { attachmentKey: key, attachmentName: name };
}

function requireTarget(targetScope: z.infer<typeof audienceSchema>, targetForm?: z.infer<typeof formSchema>, targetClassId?: number) {
  if (targetScope === "form" && !targetForm) throw new TRPCError({ code: "BAD_REQUEST", message: "Select a form for form-targeted content." });
  if (targetScope === "class" && !targetClassId) throw new TRPCError({ code: "BAD_REQUEST", message: "Select a class for class-targeted content." });
}

export const mvpRouter = router({
  calendar: router({
    list: protectedProcedure.query(async ({ ctx }) => {
      const { db, school } = await operatingSchool();
      const all = await db.select().from(calendarEvents).where(eq(calendarEvents.schoolId, school.id)).orderBy(asc(calendarEvents.startsAt)).limit(160);
      if (staffRoles.includes(ctx.user.role as (typeof staffRoles)[number])) return all;
      const studentIds = await linkedStudentIds(ctx.user.id, ctx.user.role, school.id);
      const classRows = studentIds.length ? await db.select({ classId: students.currentClassId, form: schoolClasses.form }).from(students).leftJoin(schoolClasses, eq(students.currentClassId, schoolClasses.id)).where(and(eq(students.schoolId, school.id), sql`${students.id} in (${sql.join(studentIds.map(id => sql`${id}`), sql`,`)})`)) : [];
      const classIds = classRows.map(row => row.classId).filter((value): value is number => value !== null);
      const forms = classRows.map(row => row.form).filter((value): value is NonNullable<typeof value> => value !== null);
      return all.filter(event => event.targetScope === "school" || (ctx.user.role === "parent" && event.targetScope === "parents") || (ctx.user.role === "student" && event.targetScope === "students") || (event.targetScope === "class" && Boolean(event.targetClassId && classIds.includes(event.targetClassId))) || (event.targetScope === "form" && Boolean(event.targetForm && forms.includes(event.targetForm))));
    }),
    create: protectedProcedure.input(z.object({ category: z.enum(["term", "exam", "event", "parent_meeting", "teacher_meeting", "holiday", "deadline"]), title: z.string().trim().min(2).max(180), startsAt: z.string().datetime(), endsAt: z.string().datetime().optional(), location: z.string().trim().max(180).optional(), description: z.string().trim().max(4000).optional(), targetScope: audienceSchema.default("school"), targetForm: formSchema.optional(), targetClassId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => {
      requireRole(ctx.user, leadershipRoles);
      const { db, school } = await operatingSchool();
      requireTarget(input.targetScope, input.targetForm, input.targetClassId);
      if (input.targetClassId) {
        const [targetClass] = await db.select({ id: schoolClasses.id }).from(schoolClasses).where(and(eq(schoolClasses.id, input.targetClassId), eq(schoolClasses.schoolId, school.id))).limit(1);
        if (!targetClass) throw new TRPCError({ code: "FORBIDDEN", message: "Target class is not in your school." });
      }
      if (input.endsAt && new Date(input.endsAt) < new Date(input.startsAt)) throw new TRPCError({ code: "BAD_REQUEST", message: "End time must follow the start time." });
      await db.insert(calendarEvents).values({ schoolId: school.id, createdByUserId: ctx.user.id, ...input, startsAt: new Date(input.startsAt), endsAt: input.endsAt ? new Date(input.endsAt) : null });
      const [event] = await db.select().from(calendarEvents).where(and(eq(calendarEvents.schoolId, school.id), eq(calendarEvents.title, input.title))).orderBy(desc(calendarEvents.id)).limit(1);
      await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "calendar.event_created", entityType: "calendarEvent", entityId: event?.id, metadata: { category: input.category, targetScope: input.targetScope } });
      return event;
    }),
    remove: protectedProcedure.input(z.object({ eventId: z.number().int().positive() })).mutation(async ({ ctx, input }) => {
      requireRole(ctx.user, leadershipRoles); const { db, school } = await operatingSchool();
      await db.delete(calendarEvents).where(and(eq(calendarEvents.id, input.eventId), eq(calendarEvents.schoolId, school.id)));
      await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "calendar.event_deleted", entityType: "calendarEvent", entityId: input.eventId }); return { success: true };
    }),
  }),
  notices: router({
    list: protectedProcedure.query(async ({ ctx }) => {
      const { db, school } = await operatingSchool(); const now = new Date();
      const rows = await db.select().from(announcements).where(and(eq(announcements.schoolId, school.id), lte(announcements.publishedAt, now), or(isNull(announcements.expiresAt), gt(announcements.expiresAt, now)))).orderBy(desc(announcements.isPinned), desc(announcements.publishedAt)).limit(100);
      if (staffRoles.includes(ctx.user.role as (typeof staffRoles)[number])) return rows;
      const ids = await linkedStudentIds(ctx.user.id, ctx.user.role, school.id);
      const classes = ids.length ? await db.select({ classId: students.currentClassId, form: schoolClasses.form }).from(students).leftJoin(schoolClasses, eq(students.currentClassId, schoolClasses.id)).where(and(eq(students.schoolId, school.id), sql`${students.id} in (${sql.join(ids.map(id => sql`${id}`), sql`,`)})`)) : [];
      const classIds = classes.map(row => row.classId).filter((value): value is number => value !== null); const forms = classes.map(row => row.form).filter((value): value is NonNullable<typeof value> => value !== null);
      return rows.filter(row => row.targetScope === "school" || (ctx.user.role === "parent" && row.targetScope === "parents") || (ctx.user.role === "student" && row.targetScope === "students") || (row.targetScope === "class" && Boolean(row.targetClassId && classIds.includes(row.targetClassId))) || (row.targetScope === "form" && Boolean(row.targetForm && forms.includes(row.targetForm))));
    }),
    create: protectedProcedure.input(z.object({ title: z.string().trim().min(2).max(180), body: z.string().trim().min(2).max(5000), targetScope: audienceSchema.default("school"), targetForm: formSchema.optional(), targetClassId: z.number().int().positive().optional(), publishedAt: z.string().datetime().optional(), expiresAt: z.string().datetime().optional(), isPinned: z.boolean().default(false), attachment: attachmentSchema })).mutation(async ({ ctx, input }) => {
      requireRole(ctx.user, ["super_admin", "principal", "deputy_principal", "teacher", "class_teacher"]); const { db, school } = await operatingSchool(); requireTarget(input.targetScope, input.targetForm, input.targetClassId);
      if (input.targetClassId) { const [row] = await db.select({ id: schoolClasses.id }).from(schoolClasses).where(and(eq(schoolClasses.id, input.targetClassId), eq(schoolClasses.schoolId, school.id))).limit(1); if (!row) throw new TRPCError({ code: "FORBIDDEN", message: "Target class is not in your school." }); }
      const attachment = await storeAttachment(school.id, "notices", input.attachment); const publishedAt = input.publishedAt ? new Date(input.publishedAt) : new Date(); const expiresAt = input.expiresAt ? new Date(input.expiresAt) : null;
      if (expiresAt && expiresAt <= publishedAt) throw new TRPCError({ code: "BAD_REQUEST", message: "Expiry must follow publication." });
      await db.insert(announcements).values({ schoolId: school.id, authorUserId: ctx.user.id, title: input.title, body: input.body, targetScope: input.targetScope, targetForm: input.targetForm ?? null, targetClassId: input.targetClassId ?? null, publishedAt, expiresAt, isPinned: input.isPinned, ...attachment });
      const [notice] = await db.select().from(announcements).where(and(eq(announcements.schoolId, school.id), eq(announcements.title, input.title))).orderBy(desc(announcements.id)).limit(1); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "notice.published", entityType: "announcement", entityId: notice?.id, metadata: { targetScope: input.targetScope, isPinned: input.isPinned } }); return notice;
    }),
    remove: protectedProcedure.input(z.object({ noticeId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, ["super_admin", "principal", "deputy_principal", "teacher", "class_teacher"]); const { db, school } = await operatingSchool(); await db.delete(announcements).where(and(eq(announcements.id, input.noticeId), eq(announcements.schoolId, school.id))); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "notice.deleted", entityType: "announcement", entityId: input.noticeId }); return { success: true }; }),
  }),
  assignments: router({
    list: protectedProcedure.query(async ({ ctx }) => {
      const { db, school } = await operatingSchool(); let filter = eq(assignments.schoolId, school.id);
      if (ctx.user.role === "student" || ctx.user.role === "parent") { const ids = await linkedStudentIds(ctx.user.id, ctx.user.role, school.id); const records = ids.length ? await db.select({ classId: students.currentClassId }).from(students).where(and(eq(students.schoolId, school.id), sql`${students.id} in (${sql.join(ids.map(id => sql`${id}`), sql`,`)})`)) : []; const classIds = records.map(row => row.classId).filter((id): id is number => id !== null); if (!classIds.length) return []; filter = and(eq(assignments.schoolId, school.id), sql`${assignments.classId} in (${sql.join(classIds.map(id => sql`${id}`), sql`,`)})`)!; }
      const rows = await db.select({ id: assignments.id, classId: assignments.classId, title: assignments.title, instructions: assignments.instructions, dueAt: assignments.dueAt, attachmentKey: assignments.attachmentKey, attachmentName: assignments.attachmentName, subject: subjects.name, form: schoolClasses.form, stream: schoolClasses.stream, teacherFirst: teachers.firstName, teacherLast: teachers.lastName }).from(assignments).innerJoin(subjects, eq(assignments.subjectId, subjects.id)).innerJoin(schoolClasses, eq(assignments.classId, schoolClasses.id)).innerJoin(teachers, eq(assignments.teacherId, teachers.id)).where(filter).orderBy(asc(assignments.dueAt)).limit(100);
      const ids = await linkedStudentIds(ctx.user.id, ctx.user.role, school.id); const completions = ids.length ? await db.select({ assignmentId: assignmentCompletions.assignmentId, studentId: assignmentCompletions.studentId }).from(assignmentCompletions).where(sql`${assignmentCompletions.studentId} in (${sql.join(ids.map(id => sql`${id}`), sql`,`)})`) : [];
      return rows.map(row => ({ ...row, completed: completions.some(completion => completion.assignmentId === row.id), overdue: row.dueAt.getTime() < Date.now() && !completions.some(completion => completion.assignmentId === row.id) }));
    }),
    create: protectedProcedure.input(z.object({ classId: z.number().int().positive(), subjectId: z.number().int().positive(), teacherId: z.number().int().positive().optional(), title: z.string().trim().min(2).max(180), instructions: z.string().trim().max(5000).optional(), dueAt: z.string().datetime(), attachment: attachmentSchema })).mutation(async ({ ctx, input }) => {
      requireRole(ctx.user, academicStaffRoles); const { db, school } = await operatingSchool(); const [targetClass] = await db.select({ id: schoolClasses.id }).from(schoolClasses).where(and(eq(schoolClasses.id, input.classId), eq(schoolClasses.schoolId, school.id))).limit(1); const [subject] = await db.select({ id: subjects.id }).from(subjects).where(and(eq(subjects.id, input.subjectId), eq(subjects.schoolId, school.id))).limit(1); if (!targetClass || !subject) throw new TRPCError({ code: "FORBIDDEN", message: "Class and subject must belong to your school." });
      const teacherId = input.teacherId ?? (await db.select({ id: teachers.id }).from(teachers).where(and(eq(teachers.userId, ctx.user.id), eq(teachers.schoolId, school.id))).limit(1))[0]?.id; if (!teacherId) throw new TRPCError({ code: "BAD_REQUEST", message: "Select a teacher profile for this assignment." }); const [teacher] = await db.select({ id: teachers.id }).from(teachers).where(and(eq(teachers.id, teacherId), eq(teachers.schoolId, school.id))).limit(1); if (!teacher) throw new TRPCError({ code: "FORBIDDEN", message: "Teacher is not in your school." });
      const attachment = await storeAttachment(school.id, "assignments", input.attachment); await db.insert(assignments).values({ schoolId: school.id, classId: input.classId, subjectId: input.subjectId, teacherId, title: input.title, instructions: input.instructions ?? null, dueAt: new Date(input.dueAt), ...attachment }); const [assignment] = await db.select().from(assignments).where(and(eq(assignments.schoolId, school.id), eq(assignments.title, input.title))).orderBy(desc(assignments.id)).limit(1); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "assignment.created", entityType: "assignment", entityId: assignment?.id, metadata: { classId: input.classId, subjectId: input.subjectId } }); return assignment;
    }),
    update: protectedProcedure.input(z.object({ assignmentId: z.number().int().positive(), title: z.string().trim().min(2).max(180).optional(), instructions: z.string().trim().max(5000).nullable().optional(), dueAt: z.string().datetime().optional() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, academicStaffRoles); const { db, school } = await operatingSchool(); const [assignment] = await db.select({ id: assignments.id, teacherId: assignments.teacherId }).from(assignments).where(and(eq(assignments.id, input.assignmentId), eq(assignments.schoolId, school.id))).limit(1); if (!assignment) throw new TRPCError({ code: "NOT_FOUND", message: "Assignment not found in your school." }); const [ownTeacher] = await db.select({ id: teachers.id }).from(teachers).where(and(eq(teachers.userId, ctx.user.id), eq(teachers.schoolId, school.id))).limit(1); if (!leadershipRoles.includes(ctx.user.role as (typeof leadershipRoles)[number]) && assignment.teacherId !== ownTeacher?.id) throw new TRPCError({ code: "FORBIDDEN", message: "You can only edit assignments you created." }); const { assignmentId: _assignmentId, dueAt, ...changes } = input; await db.update(assignments).set({ ...changes, ...(dueAt ? { dueAt: new Date(dueAt) } : {}) }).where(eq(assignments.id, assignment.id)); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "assignment.updated", entityType: "assignment", entityId: assignment.id }); return { success: true }; }),
    remove: protectedProcedure.input(z.object({ assignmentId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, academicStaffRoles); const { db, school } = await operatingSchool(); const [assignment] = await db.select({ id: assignments.id, teacherId: assignments.teacherId }).from(assignments).where(and(eq(assignments.id, input.assignmentId), eq(assignments.schoolId, school.id))).limit(1); if (!assignment) throw new TRPCError({ code: "NOT_FOUND", message: "Assignment not found in your school." }); const [ownTeacher] = await db.select({ id: teachers.id }).from(teachers).where(and(eq(teachers.userId, ctx.user.id), eq(teachers.schoolId, school.id))).limit(1); if (!leadershipRoles.includes(ctx.user.role as (typeof leadershipRoles)[number]) && assignment.teacherId !== ownTeacher?.id) throw new TRPCError({ code: "FORBIDDEN", message: "You can only delete assignments you created." }); await db.delete(assignments).where(eq(assignments.id, assignment.id)); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "assignment.deleted", entityType: "assignment", entityId: assignment.id }); return { success: true }; }),
    complete: protectedProcedure.input(z.object({ assignmentId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (ctx.user.role !== "student") throw new TRPCError({ code: "FORBIDDEN", message: "Only learners can mark assignments complete." }); const { db, school } = await operatingSchool(); const ids = await linkedStudentIds(ctx.user.id, ctx.user.role, school.id); const [assignment] = await db.select({ id: assignments.id, classId: assignments.classId }).from(assignments).where(and(eq(assignments.id, input.assignmentId), eq(assignments.schoolId, school.id))).limit(1); const matching = ids.length ? await db.select({ id: students.id }).from(students).where(and(eq(students.schoolId, school.id), eq(students.currentClassId, assignment?.classId ?? -1), sql`${students.id} in (${sql.join(ids.map(id => sql`${id}`), sql`,`)})`)) : []; if (!assignment || !matching[0]) throw new TRPCError({ code: "FORBIDDEN", message: "Assignment is not available to your learner account." }); await db.insert(assignmentCompletions).values({ assignmentId: assignment.id, studentId: matching[0].id }).onDuplicateKeyUpdate({ set: { completedAt: new Date() } }); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "assignment.completed", entityType: "assignment", entityId: assignment.id }); return { success: true }; }),
  }),
  studentSearch: protectedProcedure.input(z.object({ query: z.string().trim().max(80).optional(), form: formSchema.optional(), stream: z.string().trim().max(40).optional() })).query(async ({ ctx, input }) => { requireRole(ctx.user, staffRoles); const { db, school } = await operatingSchool(); const query = input.query ? `%${input.query}%` : "%"; return db.select({ id: students.id, firstName: students.firstName, lastName: students.lastName, admissionNo: students.admissionNo, form: schoolClasses.form, stream: schoolClasses.stream, status: students.status }).from(students).leftJoin(schoolClasses, eq(students.currentClassId, schoolClasses.id)).where(and(eq(students.schoolId, school.id), or(like(students.firstName, query), like(students.lastName, query), like(students.admissionNo, query)), ...(input.form ? [eq(schoolClasses.form, input.form)] : []), ...(input.stream ? [eq(schoolClasses.stream, input.stream)] : []))).orderBy(asc(students.lastName), asc(students.firstName)).limit(50); }),
  bulk: router({
    importStudents: protectedProcedure.input(z.object({ rows: z.array(z.object({ admissionNo: z.string().trim().min(2).max(40), firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), classId: z.number().int().positive().optional(), enrolledOn: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional() })).min(1).max(200) })).mutation(async ({ ctx, input }) => {
      requireRole(ctx.user, leadershipRoles); const { db, school } = await operatingSchool(); const classIds = Array.from(new Set(input.rows.map(row => row.classId).filter((id): id is number => Boolean(id)))); const classRows = classIds.length ? await db.select({ id: schoolClasses.id }).from(schoolClasses).where(and(eq(schoolClasses.schoolId, school.id), inArray(schoolClasses.id, classIds))) : []; const validClassIds = new Set(classRows.map(row => row.id)); const admissionNos = input.rows.map(row => row.admissionNo.toUpperCase()); const existing = await db.select({ admissionNo: students.admissionNo }).from(students).where(inArray(students.admissionNo, admissionNos)); const existingNos = new Set(existing.map(row => row.admissionNo.toUpperCase())); const seen = new Set<string>(); const errors = input.rows.flatMap((row, index) => { const admissionNo = row.admissionNo.toUpperCase(); const rowErrors = []; if (seen.has(admissionNo) || existingNos.has(admissionNo)) rowErrors.push("duplicate admission number"); if (row.classId && !validClassIds.has(row.classId)) rowErrors.push("class is not in this school"); seen.add(admissionNo); return rowErrors.length ? [{ row: index + 2, message: rowErrors.join(", ") }] : []; }); if (errors.length) return { imported: 0, errors };
      await db.insert(students).values(input.rows.map(row => ({ schoolId: school.id, admissionNo: row.admissionNo.toUpperCase(), firstName: row.firstName, lastName: row.lastName, currentClassId: row.classId ?? null, enrolledOn: new Date(`${row.enrolledOn ?? new Date().toISOString().slice(0, 10)}T00:00:00.000Z`) }))); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "students.bulk_imported", entityType: "student", metadata: { imported: input.rows.length } }); return { imported: input.rows.length, errors: [] as Array<{ row: number; message: string }> };
    }),
    assignClass: protectedProcedure.input(z.object({ studentIds: z.array(z.number().int().positive()).min(1).max(500), classId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, leadershipRoles); const { db, school } = await operatingSchool(); const [targetClass] = await db.select({ id: schoolClasses.id }).from(schoolClasses).where(and(eq(schoolClasses.id, input.classId), eq(schoolClasses.schoolId, school.id))).limit(1); if (!targetClass) throw new TRPCError({ code: "FORBIDDEN", message: "Target class is not in this school." }); const rows = await db.select({ id: students.id }).from(students).where(and(eq(students.schoolId, school.id), inArray(students.id, input.studentIds))); if (rows.length !== input.studentIds.length) throw new TRPCError({ code: "FORBIDDEN", message: "Every learner must belong to your school." }); await db.update(students).set({ currentClassId: targetClass.id }).where(and(eq(students.schoolId, school.id), inArray(students.id, input.studentIds))); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "students.bulk_class_assigned", entityType: "student", metadata: { classId: targetClass.id, count: input.studentIds.length } }); return { success: true, count: input.studentIds.length }; }),
  }),
  recent: router({
    list: protectedProcedure.query(async ({ ctx }) => { const { db, school } = await operatingSchool(); return db.select().from(recentViews).where(and(eq(recentViews.userId, ctx.user.id), eq(recentViews.schoolId, school.id))).orderBy(desc(recentViews.viewedAt)).limit(12); }),
    record: protectedProcedure.input(z.object({ entityType: z.enum(["student", "class", "payment", "report", "assignment"]), entityId: z.string().min(1).max(80), label: z.string().min(1).max(180) })).mutation(async ({ ctx, input }) => { const { db, school } = await operatingSchool(); await db.insert(recentViews).values({ schoolId: school.id, userId: ctx.user.id, ...input }).onDuplicateKeyUpdate({ set: { label: input.label, viewedAt: new Date() } }); return { success: true }; }),
  }),
  messaging: router({
    contacts: protectedProcedure.query(async ({ ctx }) => { const { db, school } = await operatingSchool(); const rows = await db.select({ id: users.id, name: users.name, email: users.email, role: users.role }).from(users).where(and(eq(users.schoolId, school.id), sql`${users.id} <> ${ctx.user.id}`)).orderBy(asc(users.name)).limit(200); return rows.filter(row => (leadershipRoles.includes(ctx.user.role as (typeof leadershipRoles)[number]) && ["teacher", "class_teacher", "parent"].includes(row.role)) || (academicStaffRoles.includes(ctx.user.role as (typeof academicStaffRoles)[number]) && row.role === "parent") || (ctx.user.role === "parent" && leadershipRoles.includes(row.role as (typeof leadershipRoles)[number]))); }),
    inbox: protectedProcedure.query(async ({ ctx }) => { const { db, school } = await operatingSchool(); return db.select({ id: messages.id, subject: messages.subject, body: messages.body, sentAt: messages.sentAt, readAt: messages.readAt, senderName: users.name, senderRole: users.role }).from(messages).innerJoin(users, eq(messages.senderUserId, users.id)).where(and(eq(messages.schoolId, school.id), eq(messages.recipientUserId, ctx.user.id))).orderBy(desc(messages.sentAt)).limit(80); }),
    sent: protectedProcedure.query(async ({ ctx }) => { const { db, school } = await operatingSchool(); return db.select({ id: messages.id, subject: messages.subject, body: messages.body, sentAt: messages.sentAt, recipientName: users.name, recipientRole: users.role }).from(messages).innerJoin(users, eq(messages.recipientUserId, users.id)).where(and(eq(messages.schoolId, school.id), eq(messages.senderUserId, ctx.user.id))).orderBy(desc(messages.sentAt)).limit(80); }),
    send: protectedProcedure.input(z.object({ recipientUserId: z.number().int().positive(), subject: z.string().trim().min(2).max(180), body: z.string().trim().min(1).max(4000) })).mutation(async ({ ctx, input }) => { const { db, school } = await operatingSchool(); const [recipient] = await db.select({ id: users.id, schoolId: users.schoolId, role: users.role }).from(users).where(eq(users.id, input.recipientUserId)).limit(1); if (!recipient || recipient.schoolId !== school.id || recipient.id === ctx.user.id) throw new TRPCError({ code: "FORBIDDEN", message: "Recipient is not available in your school." }); const permitted = (leadershipRoles.includes(ctx.user.role as (typeof leadershipRoles)[number]) && ["teacher", "class_teacher", "parent"].includes(recipient.role)) || (academicStaffRoles.includes(ctx.user.role as (typeof academicStaffRoles)[number]) && recipient.role === "parent") || (ctx.user.role === "parent" && leadershipRoles.includes(recipient.role as (typeof leadershipRoles)[number])); if (!permitted) throw new TRPCError({ code: "FORBIDDEN", message: "This role pairing is not permitted for internal messaging." }); await db.insert(messages).values({ schoolId: school.id, senderUserId: ctx.user.id, recipientUserId: recipient.id, subject: input.subject, body: input.body }); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "message.sent", entityType: "message", metadata: { recipientRole: recipient.role } }); return { success: true }; }),
    markRead: protectedProcedure.input(z.object({ messageId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const { db, school } = await operatingSchool(); await db.update(messages).set({ readAt: new Date() }).where(and(eq(messages.id, input.messageId), eq(messages.schoolId, school.id), eq(messages.recipientUserId, ctx.user.id))); return { success: true }; }),
  }),
  branding: router({
    get: protectedProcedure.query(async () => { const { school } = await operatingSchool(); return { name: school.name, logoKey: school.logoKey, motto: school.motto, phone: school.phone, email: school.email, address: school.address, website: school.website, primaryColor: school.primaryColor, accentColor: school.accentColor }; }),
    update: protectedProcedure.input(z.object({ motto: z.string().trim().max(180).nullable().optional(), phone: z.string().trim().max(20).nullable().optional(), email: z.string().email().nullable().optional(), address: z.string().trim().max(1000).nullable().optional(), website: z.string().url().max(255).nullable().optional(), primaryColor: z.string().regex(/^#[0-9A-Fa-f]{6}$/).nullable().optional(), accentColor: z.string().regex(/^#[0-9A-Fa-f]{6}$/).nullable().optional() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, ["super_admin", "principal"]); const { db, school } = await operatingSchool(); await db.update(schools).set(input).where(eq(schools.id, school.id)); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "school.branding_updated", entityType: "school", entityId: school.id }); return { success: true }; }),
  }),
  ids: router({
    generate: protectedProcedure.input(z.object({ studentId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireRole(ctx.user, leadershipRoles); const { db, school } = await operatingSchool(); const [student] = await db.select({ id: students.id, schoolId: students.schoolId }).from(students).where(and(eq(students.id, input.studentId), eq(students.schoolId, school.id))).limit(1); if (!student) throw new TRPCError({ code: "NOT_FOUND", message: "Learner not found in your school." }); const [year] = await db.select({ id: academicYears.id }).from(academicYears).where(and(eq(academicYears.schoolId, school.id), eq(academicYears.isActive, true))).limit(1); const existing = await db.select().from(studentIdCards).where(and(eq(studentIdCards.schoolId, school.id), eq(studentIdCards.studentId, student.id), year ? eq(studentIdCards.academicYearId, year.id) : isNull(studentIdCards.academicYearId))).limit(1); if (existing[0]) return existing[0]; const token = nanoid(24); await db.insert(studentIdCards).values({ schoolId: school.id, studentId: student.id, academicYearId: year?.id ?? null, verificationToken: token, generatedByUserId: ctx.user.id }); const [card] = await db.select().from(studentIdCards).where(eq(studentIdCards.verificationToken, token)).limit(1); await writeAuditLog({ schoolId: school.id, actorUserId: ctx.user.id, action: "student.id_generated", entityType: "student", entityId: student.id }); return card; }),
    preview: protectedProcedure.input(z.object({ cardId: z.number().int().positive() })).query(async ({ ctx, input }) => { requireRole(ctx.user, leadershipRoles); const { db, school } = await operatingSchool(); const rows = await db.select({ id: studentIdCards.id, verificationToken: studentIdCards.verificationToken, schoolName: schools.name, schoolLogoKey: schools.logoKey, motto: schools.motto, primaryColor: schools.primaryColor, accentColor: schools.accentColor, firstName: students.firstName, middleName: students.middleName, lastName: students.lastName, photoKey: students.photoKey, admissionNo: students.admissionNo, form: schoolClasses.form, stream: schoolClasses.stream, academicYear: academicYears.name }).from(studentIdCards).innerJoin(schools, eq(studentIdCards.schoolId, schools.id)).innerJoin(students, eq(studentIdCards.studentId, students.id)).leftJoin(schoolClasses, eq(students.currentClassId, schoolClasses.id)).leftJoin(academicYears, eq(studentIdCards.academicYearId, academicYears.id)).where(and(eq(studentIdCards.id, input.cardId), eq(studentIdCards.schoolId, school.id))).limit(1); if (!rows[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Student ID card not found in your school." }); return rows[0]; }),
    verify: publicProcedure.input(z.object({ token: z.string().min(10).max(64) })).query(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const rows = await db.select({ schoolName: schools.name, studentName: sql<string>`concat(${students.firstName}, ' ', ${students.lastName})`, admissionNo: students.admissionNo, form: schoolClasses.form, stream: schoolClasses.stream, generatedAt: studentIdCards.generatedAt }).from(studentIdCards).innerJoin(schools, eq(studentIdCards.schoolId, schools.id)).innerJoin(students, eq(studentIdCards.studentId, students.id)).leftJoin(schoolClasses, eq(students.currentClassId, schoolClasses.id)).where(eq(studentIdCards.verificationToken, input.token)).limit(1); const card = rows[0]; return card ? { verified: true as const, ...card } : { verified: false as const }; }),
  }),
  dashboard: protectedProcedure.query(async ({ ctx }) => { const { db, school } = await operatingSchool(); const now = new Date(); const upcomingEvents = await db.select({ id: calendarEvents.id, title: calendarEvents.title, category: calendarEvents.category, startsAt: calendarEvents.startsAt }).from(calendarEvents).where(and(eq(calendarEvents.schoolId, school.id), gte(calendarEvents.startsAt, now))).orderBy(asc(calendarEvents.startsAt)).limit(5); const activities = await db.select({ id: auditLogs.id, action: auditLogs.action, entityType: auditLogs.entityType, createdAt: auditLogs.createdAt, actorName: users.name }).from(auditLogs).leftJoin(users, eq(auditLogs.actorUserId, users.id)).where(eq(auditLogs.schoolId, school.id)).orderBy(desc(auditLogs.createdAt)).limit(8); const missingMarks = await db.select({ count: sql<number>`count(*)` }).from(assignments).where(and(eq(assignments.schoolId, school.id), gte(assignments.dueAt, now))); const overdueFees = await db.select({ count: sql<number>`count(*)` }).from(studentFeeAccounts).innerJoin(feeStructures, eq(studentFeeAccounts.feeStructureId, feeStructures.id)).where(and(eq(feeStructures.schoolId, school.id), sql`${studentFeeAccounts.status} in ('overdue','partial')`)); return { upcomingEvents, activity: activities, alerts: [{ kind: "fees", count: Number(overdueFees[0]?.count ?? 0), label: "Fee accounts need follow-up" }, { kind: "assignments", count: Number(missingMarks[0]?.count ?? 0), label: "Active assignment deadlines" }] }; }),
});
