import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ShieldAlert, ShieldCheck } from "lucide-react";

export default function CardVerification() {
  const token = new URLSearchParams(window.location.search).get("token") ?? "";
  const verification = trpc.school.mvp.ids.verify.useQuery({ token }, { enabled: token.length >= 10 });
  return <main className="grid min-h-screen place-items-center bg-[#f4f7f5] p-4 dark:bg-[#10201b]"><Card className="w-full max-w-md border-emerald-950/10 bg-white shadow-[0_24px_70px_-34px_rgba(10,65,48,0.35)] dark:border-white/8 dark:bg-[#172420]"><CardHeader className="border-b border-emerald-950/8 bg-[#0d4437] text-white"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e4bd69] text-[#143b31]"><ShieldCheck className="h-5 w-5" /></div><CardTitle className="mt-4 text-xl">Student ID verification</CardTitle><CardDescription className="text-emerald-100/75">This page confirms a card identity without exposing private school records.</CardDescription></CardHeader><CardContent className="p-6">{!token ? <Result invalid message="No verification token was provided." /> : verification.isLoading ? <div className="space-y-3"><Skeleton className="h-6 w-2/3" /><Skeleton className="h-4 w-full" /><Skeleton className="h-4 w-4/5" /></div> : verification.data?.verified ? <div><div className="flex items-center gap-2 text-emerald-700 dark:text-emerald-300"><CheckCircle2 className="h-5 w-5" /><p className="font-semibold">Valid student ID</p></div><p className="mt-5 text-xl font-semibold text-[#143b31] dark:text-emerald-50">{verification.data.studentName}</p><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">School</dt><dd className="text-right font-medium">{verification.data.schoolName}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Admission number</dt><dd className="font-mono text-right font-medium">{verification.data.admissionNo}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Class</dt><dd className="text-right font-medium">{verification.data.form && verification.data.stream ? `${verification.data.form} · ${verification.data.stream}` : "Not assigned"}</dd></div></dl><p className="mt-6 text-xs leading-5 text-slate-500 dark:text-slate-400">Only verification-safe identity information is displayed here.</p></div> : <Result invalid message={verification.error?.message || "This student ID is invalid or no longer available."} />}</CardContent></Card></main>;
}

function Result({ invalid, message }: { invalid: boolean; message: string }) { return <div className="text-center"><ShieldAlert className="mx-auto h-10 w-10 text-rose-600" /><p className="mt-4 font-semibold text-rose-800 dark:text-rose-300">{invalid ? "Unable to verify this card" : "Verification unavailable"}</p><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{message}</p></div>; }
