import fs from "node:fs";

const path = "/home/ubuntu/kenyan-school-management/client/src/pages/Home.tsx";
let source = fs.readFileSync(path, "utf8");

const feeFunctions = String.raw`
function FeeStructureEntry() {
  const config = trpc.school.academics.config.useQuery();
  const utils = trpc.useUtils();
  const create = trpc.school.finance.createFeeStructure.useMutation({ onSuccess: result => { toast.success(\`Fee structure saved; \${result.accountsCreated} account(s) assigned. Ready for the next fee item.\`); setForm({ yearId: "", termId: "", classId: "", name: "", amount: "", dueDate: today }); utils.school.finance.mine.invalidate(); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState({ yearId: "", termId: "", classId: "", name: "", amount: "", dueDate: today });
  const years = config.data?.academicYears ?? [];
  const terms = config.data?.terms ?? [];
  const classes = config.data?.classes ?? [];
  return <WorkflowCard title="Create fee structure" copy="Set the KES fee item once for an academic year, term and class. Assigned learner accounts are created automatically."><form className="grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); if (![form.yearId, form.termId, form.classId, form.name, form.amount].every(Boolean)) return toast.error("Complete all fee-structure fields."); create.mutate({ academicYearId: Number(form.yearId), termId: Number(form.termId), classId: Number(form.classId), name: form.name, amount: Number(form.amount), dueDate: form.dueDate }); }}><YearSelect years={years} value={form.yearId} onChange={value => setForm({ ...form, yearId: value, termId: "" })} /><TermSelect terms={terms} yearId={form.yearId} value={form.termId} onChange={value => setForm({ ...form, termId: value })} /><ClassSelect classes={classes} value={form.classId} onChange={value => setForm({ ...form, classId: value })} /><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Fee item name, e.g. Tuition" className="rounded-xl" required /><Input type="number" min="1" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })} placeholder="Amount (KES)" className="rounded-xl" required /><Input type="date" value={form.dueDate} onChange={event => setForm({ ...form, dueDate: event.target.value })} className="rounded-xl" /><Button className="rounded-xl bg-[#0d4437] text-white sm:col-span-2" disabled={create.isPending}>{create.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}Save fee structure</Button></form></WorkflowCard>;
}

function FeeCollectionEntry() {
  const accounts = trpc.school.finance.mine.useQuery();
  const utils = trpc.useUtils();
  const record = trpc.school.finance.recordPayment.useMutation({ onSuccess: result => { toast.success(\`Payment received. Receipt \${result.receiptNo}. Ready for the next payment.\`); setForm({ accountId: "", amount: "", method: "mpesa", reference: "", date: today }); utils.school.finance.mine.invalidate(); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState({ accountId: "", amount: "", method: "mpesa" as "mpesa" | "bank" | "cash" | "other", reference: "", date: today });
  return <WorkflowCard title="Record payment & issue receipt" copy="All M-Pesa, bank, cash and other payments are recorded in Fees. A receipt number is generated automatically."><form className="grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); if (!form.accountId || Number(form.amount) <= 0) return toast.error("Select a fee account and enter a payment amount."); record.mutate({ studentFeeAccountId: Number(form.accountId), amount: Number(form.amount), method: form.method, reference: form.reference || undefined, paymentDate: form.date }); }}><Select value={form.accountId} onValueChange={value => setForm({ ...form, accountId: value })}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Select fee account" /></SelectTrigger><SelectContent>{(accounts.data ?? []).map(account => <SelectItem key={account.id} value={String(account.id)}>{account.firstName} {account.lastName} · {account.feeName} · {formatKes(Number(account.due) - Number(account.paid))} balance</SelectItem>)}</SelectContent></Select><Input type="number" min="1" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })} placeholder="Payment amount (KES)" className="rounded-xl" required /><Select value={form.method} onValueChange={value => setForm({ ...form, method: value as typeof form.method })}><SelectTrigger className="rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="mpesa">M-Pesa</SelectItem><SelectItem value="bank">Bank</SelectItem><SelectItem value="cash">Cash</SelectItem><SelectItem value="other">Other</SelectItem></SelectContent></Select><Input value={form.reference} onChange={event => setForm({ ...form, reference: event.target.value })} placeholder="Reference / M-Pesa code" className="rounded-xl" /><Input type="date" value={form.date} onChange={event => setForm({ ...form, date: event.target.value })} className="rounded-xl" /><Button className="rounded-xl bg-[#0d4437] text-white sm:col-span-2" disabled={record.isPending}>{record.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ReceiptText className="mr-2 h-4 w-4" />}Record payment & issue receipt</Button></form></WorkflowCard>;
}

function FeeBalanceEntry() {
  const accounts = trpc.school.finance.mine.useQuery();
  const utils = trpc.useUtils();
  const adjust = trpc.school.finance.adjustAccount.useMutation({ onSuccess: () => { toast.success("Fee balance corrected and audited. Ready for the next correction."); setForm({ accountId: "", amountDue: "", reason: "" }); utils.school.finance.mine.invalidate(); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState({ accountId: "", amountDue: "", reason: "" });
  return <WorkflowCard title="Update a learner fee balance" copy="Correct amount due without changing recorded payments. A reason is required and the correction is audit logged."><form className="grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); if (!form.accountId || Number(form.amountDue) < 0 || form.reason.trim().length < 5) return toast.error("Select an account, enter the corrected amount, and give a reason."); if (!window.confirm("Save this fee balance correction? Recorded payments will not change.")) return; adjust.mutate({ studentFeeAccountId: Number(form.accountId), amountDue: Number(form.amountDue), reason: form.reason.trim() }); }}><Select value={form.accountId} onValueChange={value => { const account = (accounts.data ?? []).find(row => row.id === Number(value)); setForm({ accountId: value, amountDue: account ? String(account.due) : "", reason: "" }); }}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Select learner fee account" /></SelectTrigger><SelectContent>{(accounts.data ?? []).map(account => <SelectItem key={account.id} value={String(account.id)}>{account.firstName} {account.lastName} · {account.feeName} · due {formatKes(account.due)}</SelectItem>)}</SelectContent></Select><Input type="number" min="0" value={form.amountDue} onChange={event => setForm({ ...form, amountDue: event.target.value })} placeholder="Correct amount due (KES)" className="rounded-xl" required /><Textarea value={form.reason} onChange={event => setForm({ ...form, reason: event.target.value })} placeholder="Reason for correction, e.g. approved bursary" className="min-h-24 rounded-xl sm:col-span-2" required /><Button className="rounded-xl bg-[#0d4437] text-white sm:col-span-2" disabled={adjust.isPending}>{adjust.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <WalletCards className="mr-2 h-4 w-4" />}Save audited balance correction</Button></form></WorkflowCard>;
}

function FeesPanel() {
  const { user } = useAuth();
  const staff = ["super_admin", "principal", "bursar"].includes(user?.role ?? "");
  const accounts = trpc.school.finance.mine.useQuery();
  if (!staff) return <><SectionHeading eyebrow="KES finance" title="Your fee status" description="This view only displays fee accounts linked to your learner profile." /><Card className="border-emerald-950/8 bg-white/85 dark:border-white/8 dark:bg-[#172420]"><CardContent className="p-5"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y border-emerald-950/7 text-[10px] uppercase tracking-[0.14em] text-slate-400"><tr><th className="px-3 py-3">Fee item</th><th className="px-3 py-3 text-right">Due</th><th className="px-3 py-3 text-right">Paid</th><th className="px-3 py-3 text-right">Balance</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{accounts.data?.length ? accounts.data.map(row => <tr key={row.id} className="border-b border-emerald-950/6 dark:border-white/7"><td className="px-3 py-3.5 font-semibold">{row.feeName}</td><td className="px-3 py-3.5 text-right">{formatKes(row.due)}</td><td className="px-3 py-3.5 text-right text-emerald-700 dark:text-emerald-300">{formatKes(row.paid)}</td><td className="px-3 py-3.5 text-right font-semibold">{formatKes(Number(row.due) - Number(row.paid))}</td><td className="px-3 py-3.5"><StatusPill value={row.status} /></td></tr>) : <EmptyTable colSpan={5} label="No linked fee accounts are available yet." />}</tbody></table></div></CardContent></Card></>;
  return <><SectionHeading eyebrow="KES finance" title="Fees · one workspace" description="Every fee action is grouped here: set up structures, create learner accounts, record payments, correct balances, print documents, and export collection records."><Button variant="outline" className="rounded-xl bg-white dark:bg-transparent" onClick={() => downloadCsv("fee-accounts.csv", (accounts.data ?? []).map(row => ({ student: \`\${row.firstName} \${row.lastName}\`, admissionNo: row.admissionNo, fee: row.feeName, due: row.due, paid: row.paid, balance: Number(row.due) - Number(row.paid), status: row.status })))}><SquareArrowOutUpRight className="mr-2 h-4 w-4" />Export Excel</Button></SectionHeading><div className="mb-6 grid gap-5 xl:grid-cols-2"><FeeStructureEntry /><FeeAccountEntry /><FeeCollectionEntry /><FeeBalanceEntry /><FinanceDocuments /></div><Card className="border-emerald-950/8 bg-white/85 dark:border-white/8 dark:bg-[#172420]"><CardHeader><CardTitle className="text-base">Learner fee accounts</CardTitle><CardDescription>Balances, payment status and printable documents all begin here.</CardDescription></CardHeader><CardContent className="p-4 sm:p-5"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y border-emerald-950/7 text-[10px] uppercase tracking-[0.14em] text-slate-400"><tr><th className="px-3 py-3">Learner</th><th className="px-3 py-3">Fee item</th><th className="px-3 py-3 text-right">Due</th><th className="px-3 py-3 text-right">Paid</th><th className="px-3 py-3 text-right">Balance</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{accounts.isLoading ? <EmptyTable colSpan={6} label="Loading fee accounts…" /> : accounts.data?.length ? accounts.data.map(row => <tr key={row.id} className="border-b border-emerald-950/6 dark:border-white/7"><td className="px-3 py-3.5"><p className="font-semibold">{row.firstName} {row.lastName}</p><p className="mt-0.5 font-mono text-xs text-slate-500">{row.admissionNo}</p></td><td className="px-3 py-3.5 text-slate-600 dark:text-slate-300">{row.feeName}</td><td className="px-3 py-3.5 text-right">{formatKes(row.due)}</td><td className="px-3 py-3.5 text-right text-emerald-700 dark:text-emerald-300">{formatKes(row.paid)}</td><td className="px-3 py-3.5 text-right font-semibold text-[#0d4437] dark:text-emerald-300">{formatKes(Number(row.due) - Number(row.paid))}</td><td className="px-3 py-3.5"><StatusPill value={row.status} /></td></tr>) : <EmptyTable colSpan={6} label="No fee accounts are currently available." />}</tbody></table></div></CardContent></Card></>;
}
`;

const feePattern = /function FeesPanel\(\) \{[\s\S]*?\n\}\n\nfunction TimetablePanel/;
if (!feePattern.test(source)) throw new Error("FeesPanel boundary not found");
source = source.replace(feePattern, `${feeFunctions}\nfunction TimetablePanel`);

const departmentFunction = String.raw`
function DepartmentEntry() {
  const { user } = useAuth();
  const canManage = ["super_admin", "principal", "deputy_principal"].includes(user?.role ?? "");
  const config = trpc.school.academics.config.useQuery(undefined, { enabled: canManage });
  const utils = trpc.useUtils();
  const create = trpc.school.academics.createDepartment.useMutation({ onSuccess: () => { toast.success("Department created. Ready for the next department."); setForm({ name: "", code: "" }); utils.school.academics.config.invalidate(); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState({ name: "", code: "" });
  if (!canManage) return null;
  return <Card className="mb-5 border-emerald-950/8 bg-white/85 dark:border-white/8 dark:bg-[#172420]"><CardHeader><CardTitle className="text-base">Departments</CardTitle><CardDescription>Keep department creation here with academic configuration. Codes are normalized to uppercase and saved with an audit trail.</CardDescription></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-[1fr_180px_auto]" onSubmit={event => { event.preventDefault(); if (!form.name.trim() || !form.code.trim()) return toast.error("Enter a department name and code."); create.mutate({ name: form.name.trim(), code: form.code.trim() }); }}><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Department name, e.g. Sciences" className="rounded-xl" required /><Input value={form.code} onChange={event => setForm({ ...form, code: event.target.value.toUpperCase() })} placeholder="Code, e.g. SCI" className="rounded-xl" required /><Button className="rounded-xl bg-[#0d4437] text-white" disabled={create.isPending}>{create.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}Add department</Button></form><div className="mt-4 flex flex-wrap gap-2">{(config.data?.departments ?? []).length ? (config.data?.departments ?? []).map(row => <Badge key={row.id} variant="secondary" className="rounded-full bg-[#e8f1ec] px-3 py-1 text-[#0d4437] dark:bg-emerald-950/60 dark:text-emerald-300">{row.code} · {row.name}</Badge>) : <EmptyText label="No departments have been added yet." />}</div></CardContent></Card>;
}
`;
const departmentPattern = /function PortalAcademicPanel/;
source = source.replace(departmentPattern, `${departmentFunction}\nfunction PortalAcademicPanel`);

source = source.replace('{ id: "operations", label: "Operations", icon: ListChecks }, { id: "advanced", label: "Control centre", icon: Settings2 }, ...(role !== "bursar" ? [{ id: "manage", label: "Manage records", icon: Settings2 }] : []),', '{ id: "operations", label: "Daily tasks", icon: ListChecks }, { id: "advanced", label: "Insights & alerts", icon: Settings2 }, ...(role !== "bursar" ? [{ id: "manage", label: "Record maintenance", icon: Settings2 }] : []),');
source = source.replace('academics: <AcademicsPanel />,', 'academics: <><AcademicsPanel /><DepartmentEntry /></>,');

const managementFeeTrigger = /<TabsTrigger value="fees" className="rounded-lg">Fee balances<\/TabsTrigger>/;
source = source.replace(managementFeeTrigger, '');
source = source.replace(/<TabsContent value="fees">[\s\S]*?<\/TabsContent>/, '');

source = source.replace(/<WorkflowCard title="Fee structure"[\s\S]*?<\/WorkflowCard>/, '');
source = source.replace(/<WorkflowCard title="Payment & receipt"[\s\S]*?<\/WorkflowCard>/, '');

fs.writeFileSync(path, source);
console.log("Reorganized primary module workflows and added department entry.");
