import { ClipboardCopy, KeyRound, Loader2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

type Account = { id: number; name: string | null; email: string | null; role: string; lastSignedIn: Date };

export default function LocalAccountProvisioning({ accounts }: { accounts: Account[] }) {
  const [issued, setIssued] = useState<{ userId: number; name: string; code: string; expiresAt: Date } | null>(null);
  const issue = trpc.auth.issueLocalSetupCode.useMutation({ onSuccess: result => { setIssued({ userId: result.user.id, name: result.user.name || "Selected account", code: result.code, expiresAt: result.expiresAt }); toast.success("One-time account code issued. Share it privately with the account holder."); }, onError: error => toast.error(error.message) });
  const copy = async () => { if (!issued) return; await navigator.clipboard?.writeText(`Account setup ID: ${issued.userId}\nOne-time code: ${issued.code}`); toast.success("Account details copied."); };
  return <Card className="border-emerald-950/8 bg-white/85 dark:border-white/8 dark:bg-[#172420]"><CardHeader><CardTitle className="text-base">Staff account setup & recovery</CardTitle><CardDescription>Issue a one-time code to an existing school staff account for first-time setup or password recovery. During recovery, staff keep their username and choose a new password; the code is shown only once and expires after 24 hours.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="space-y-2">{accounts.filter(account => account.role !== "student").map(account => <div key={account.id} className="flex flex-col justify-between gap-3 rounded-xl border border-emerald-950/7 p-3 sm:flex-row sm:items-center dark:border-white/8"><div className="min-w-0"><p className="truncate text-sm font-semibold">{account.name || "Unnamed account"}</p><p className="truncate text-xs text-slate-500">{account.email || "No email"} · {account.role.replaceAll("_", " ")}</p></div><Button size="sm" variant="outline" className="rounded-xl" disabled={issue.isPending} onClick={() => issue.mutate({ userId: account.id })}><KeyRound className="mr-1.5 h-3.5 w-3.5" />Issue setup/recovery code</Button></div>)}</div>{issued ? <div className="rounded-2xl border border-amber-300/70 bg-amber-50 p-4 dark:border-amber-900/60 dark:bg-amber-950/20"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#94651f]">Share privately with {issued.name}</p><p className="mt-2 font-mono text-sm text-[#143b31] dark:text-amber-100">Account ID: {issued.userId}</p><p className="mt-1 font-mono text-lg font-bold tracking-[0.16em] text-[#143b31] dark:text-amber-100">{issued.code}</p><p className="mt-1 text-xs text-slate-500">Expires {new Date(issued.expiresAt).toLocaleString()}</p></div><Badge className="border-0 bg-amber-200 text-amber-900">One use</Badge></div><Button size="sm" variant="outline" className="mt-3 rounded-xl" onClick={() => void copy()}><ClipboardCopy className="mr-1.5 h-3.5 w-3.5" />Copy account ID and code</Button></div> : null}{issue.isPending ? <p className="flex items-center gap-2 text-xs text-slate-500"><Loader2 className="h-3.5 w-3.5 animate-spin" />Preparing a secure setup code…</p> : null}</CardContent></Card>;
}
