import { ArrowLeft, KeyRound, LockKeyhole, Loader2, ShieldCheck, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { BRAND_LOGO_URL, BRAND_NAME, BRAND_TAGLINE } from "@/const";

type AccessMode = "learner" | "staff" | "reset" | "setup";

export default function StudentLoginCard() {
  const utils = trpc.useUtils();
  const [mode, setMode] = useState<AccessMode>("learner");
  const [schoolCode, setSchoolCode] = useState("");
  const [username, setUsername] = useState("");
  const [identifier, setIdentifier] = useState("");
  const [password, setPassword] = useState("");
  const [resetCode, setResetCode] = useState("");
  const [setupCode, setSetupCode] = useState("");
  const [setupUserId, setSetupUserId] = useState("");
  const [newUsername, setNewUsername] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const login = trpc.auth.loginStudent.useMutation({ onSuccess: async result => { toast.success(`Welcome, ${result.student.name}.`); await utils.auth.me.invalidate(); }, onError: error => toast.error(error.message) });
  const staffLogin = trpc.auth.loginLocal.useMutation({ onSuccess: async result => { toast.success(`Welcome${result.user.name ? `, ${result.user.name}` : ""}.`); await utils.auth.me.invalidate(); }, onError: error => toast.error(error.message) });
  const reset = trpc.auth.resetStudentPassword.useMutation({ onSuccess: () => { setMode("learner"); setPassword(""); setResetCode(""); setNewPassword(""); setConfirmPassword(""); toast.success("Password reset complete. Sign in with your new password."); }, onError: error => toast.error(error.message) });
  const setup = trpc.auth.completeLocalSetup.useMutation({ onSuccess: result => { setMode("staff"); setIdentifier(result.username); setSetupCode(""); setSetupUserId(""); setNewUsername(""); setNewPassword(""); setConfirmPassword(""); toast.success("Account ready. Sign in with your new username and password."); }, onError: error => toast.error(error.message) });

  const submitLearner = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); login.mutate({ schoolCode, username, password }); };
  const submitStaff = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); staffLogin.mutate({ identifier, password }); };
  const submitReset = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); reset.mutate({ schoolCode, username, resetCode, newPassword, confirmPassword }); };
  const submitSetup = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setup.mutate({ userId: Number(setupUserId), setupCode, username: newUsername, password: newPassword, confirmPassword }); };

  const schoolCodeField = (id: string) => <div><Label htmlFor={id}>School code</Label><Input id={id} value={schoolCode} onChange={event => setSchoolCode(event.target.value.toUpperCase())} autoComplete="organization" placeholder="e.g. ONY" className="mt-2 rounded-xl font-mono uppercase tracking-[0.1em]" required /><p className="mt-1.5 text-xs leading-5 text-slate-500 dark:text-slate-400">Ask your school office for the short code shown in its school profile.</p></div>;
  const title = mode === "learner" ? "Access your results." : mode === "reset" ? "Reset your password." : mode === "staff" ? "Welcome back." : "Set up your account.";
  const description = mode === "learner" ? "Enter your school code, full name, and admission number or private password." : mode === "reset" ? "Enter your school code and a one-time reset code issued by the school office." : mode === "staff" ? "Sign in with the username and password issued by your school administrator." : "Use the one-time setup code from your school administrator to create your private sign-in.";
  const busy = login.isPending || staffLogin.isPending || reset.isPending || setup.isPending;

  return <main className="grid min-h-screen place-items-center bg-[#f5f7f5] p-4 text-slate-900 dark:bg-[#101b18] dark:text-slate-100 sm:p-6"><Card className="w-full max-w-md overflow-hidden rounded-[2rem] border-emerald-950/10 bg-white shadow-[0_24px_80px_-32px_rgba(11,61,46,0.32)] dark:border-white/10 dark:bg-[#172420]"><CardHeader className="p-6 pb-4 sm:p-8 sm:pb-5"><div className="mb-5 flex items-center gap-3"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#0d4437] p-2 shadow-lg shadow-emerald-950/20"><img src={BRAND_LOGO_URL} alt={`${BRAND_NAME} logo`} className="h-full w-full object-contain" /></div><div><p className="font-serif text-lg font-semibold tracking-[-0.03em] text-[#103b31] dark:text-emerald-50">{BRAND_NAME}</p><p className="mt-0.5 text-[9px] font-semibold uppercase tracking-[0.11em] text-[#a8792c]">{BRAND_TAGLINE}</p></div></div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#ae7d2c]">{mode === "learner" || mode === "reset" ? "Learner portal" : "School access"}</p><CardTitle className="mt-3 text-3xl tracking-[-0.045em] text-[#103b31] dark:text-emerald-50">{title}</CardTitle><CardDescription className="mt-3 leading-6">{description}</CardDescription></CardHeader><CardContent className="p-6 pt-0 sm:p-8 sm:pt-0">
    {mode === "learner" ? <form className="space-y-4" onSubmit={submitLearner}>{schoolCodeField("student-school-code")}<div><Label htmlFor="student-username">Learner name</Label><Input id="student-username" value={username} onChange={event => setUsername(event.target.value)} autoComplete="username" placeholder="e.g. Amina Otieno" className="mt-2 rounded-xl" required /><p className="mt-1.5 text-xs leading-5 text-slate-500 dark:text-slate-400">Use your first, middle, and last names as recorded in the school register.</p></div><div><Label htmlFor="student-password">Admission number or current password</Label><Input id="student-password" type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" placeholder="e.g. ADM-0001" className="mt-2 rounded-xl font-mono" required /><p className="mt-1.5 text-xs leading-5 text-slate-500 dark:text-slate-400">Use your admission number until you set a custom password.</p></div><Button type="submit" size="lg" disabled={busy} className="mt-2 w-full rounded-xl bg-[#0d4437] text-white hover:bg-[#092f26]">{login.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <LockKeyhole className="mr-2 h-4 w-4" />}Sign in to results</Button><Button type="button" variant="ghost" onClick={() => setMode("reset")} className="w-full rounded-xl text-[#0d4437] hover:bg-emerald-50 hover:text-[#092f26] dark:text-emerald-300 dark:hover:bg-emerald-950/30">Forgot custom password?</Button></form> : null}
    {mode === "staff" ? <form className="space-y-4" onSubmit={submitStaff}><div><Label htmlFor="staff-identifier">Username or email</Label><Input id="staff-identifier" value={identifier} onChange={event => setIdentifier(event.target.value)} autoComplete="username" placeholder="e.g. principal" className="mt-2 rounded-xl" required /></div><div><Label htmlFor="staff-password">Password</Label><Input id="staff-password" type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" className="mt-2 rounded-xl" required /></div><Button type="submit" size="lg" disabled={busy} className="w-full rounded-xl bg-[#0d4437] text-white hover:bg-[#092f26]">{staffLogin.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <UserRound className="mr-2 h-4 w-4" />}Sign in to school workspace</Button><Button type="button" variant="ghost" onClick={() => setMode("setup")} className="w-full rounded-xl text-[#0d4437] hover:bg-emerald-50 dark:text-emerald-300">First time here? Set up your account</Button></form> : null}
    {mode === "reset" ? <form className="space-y-4" onSubmit={submitReset}>{schoolCodeField("reset-student-school-code")}<div><Label htmlFor="reset-student-username">Learner name</Label><Input id="reset-student-username" value={username} onChange={event => setUsername(event.target.value)} autoComplete="username" placeholder="e.g. Amina Otieno" className="mt-2 rounded-xl" required /></div><div><Label htmlFor="student-reset-code">One-time reset code</Label><Input id="student-reset-code" value={resetCode} onChange={event => setResetCode(event.target.value.toUpperCase())} autoComplete="one-time-code" placeholder="Enter code from school office" className="mt-2 rounded-xl font-mono uppercase tracking-[0.12em]" required /></div><div><Label htmlFor="student-reset-new-password">New password</Label><Input id="student-reset-new-password" type="password" value={newPassword} onChange={event => setNewPassword(event.target.value)} autoComplete="new-password" className="mt-2 rounded-xl" minLength={8} required /></div><div><Label htmlFor="student-reset-confirm-password">Confirm new password</Label><Input id="student-reset-confirm-password" type="password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} autoComplete="new-password" className="mt-2 rounded-xl" minLength={8} required /></div><Button type="submit" size="lg" disabled={busy} className="w-full rounded-xl bg-[#0d4437] text-white hover:bg-[#092f26]">{reset.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <KeyRound className="mr-2 h-4 w-4" />}Reset password</Button><Button type="button" variant="ghost" onClick={() => setMode("learner")} className="w-full rounded-xl text-[#0d4437] dark:text-emerald-300"><ArrowLeft className="mr-2 h-4 w-4" />Back to learner sign-in</Button></form> : null}
    {mode === "setup" ? <form className="space-y-4" onSubmit={submitSetup}><div><Label htmlFor="setup-user-id">Account setup ID</Label><Input id="setup-user-id" inputMode="numeric" value={setupUserId} onChange={event => setSetupUserId(event.target.value)} placeholder="Provided by the administrator" className="mt-2 rounded-xl font-mono" required /><p className="mt-1.5 text-xs leading-5 text-slate-500 dark:text-slate-400">Your administrator gives you this ID together with the one-time code.</p></div><div><Label htmlFor="setup-code">One-time setup code</Label><Input id="setup-code" value={setupCode} onChange={event => setSetupCode(event.target.value.toUpperCase())} autoComplete="one-time-code" className="mt-2 rounded-xl font-mono uppercase tracking-[0.12em]" required /></div><div><Label htmlFor="setup-username">Choose a username</Label><Input id="setup-username" value={newUsername} onChange={event => setNewUsername(event.target.value)} autoComplete="username" className="mt-2 rounded-xl" required /></div><div><Label htmlFor="setup-password">Create a password</Label><Input id="setup-password" type="password" value={newPassword} onChange={event => setNewPassword(event.target.value)} autoComplete="new-password" minLength={8} className="mt-2 rounded-xl" required /></div><div><Label htmlFor="setup-confirm-password">Confirm password</Label><Input id="setup-confirm-password" type="password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} autoComplete="new-password" minLength={8} className="mt-2 rounded-xl" required /></div><Button type="submit" size="lg" disabled={busy} className="w-full rounded-xl bg-[#0d4437] text-white hover:bg-[#092f26]">{setup.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <KeyRound className="mr-2 h-4 w-4" />}Create local account</Button><Button type="button" variant="ghost" onClick={() => setMode("staff")} className="w-full rounded-xl text-[#0d4437] dark:text-emerald-300"><ArrowLeft className="mr-2 h-4 w-4" />Back to staff sign-in</Button></form> : null}
    <div className="mt-5 rounded-2xl border border-emerald-950/8 bg-[#f4f7f5] p-3.5 dark:border-white/8 dark:bg-white/5"><p className="flex items-start gap-2 text-xs leading-5 text-slate-600 dark:text-slate-300"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#a8792c]" />Your account is protected by Elimubora360. Never share a password, setup code, or reset code publicly.</p></div>
    <div className="mt-6 border-t border-emerald-950/8 pt-5 text-center dark:border-white/8">{mode === "learner" ? <><p className="text-xs text-slate-500 dark:text-slate-400">School staff, parents, and administrators</p><Button type="button" variant="outline" onClick={() => setMode("staff")} className="mt-2 rounded-xl bg-white dark:bg-transparent">Use school account sign-in</Button></> : <Button type="button" variant="ghost" onClick={() => setMode("learner")} className="rounded-xl text-[#0d4437] dark:text-emerald-300"><ArrowLeft className="mr-2 h-4 w-4" />Learner portal</Button>}</div>
  </CardContent></Card></main>;
}
